### ISSUE TITLE
Advice Button Misplaced When Text is Too Large

### ISSUE THREAD

**Issue by DhirajMuppineti** [Omkar-Shirwadkar/advice-app-react#1]
When the text within the window becomes too large, the "GIVE ME ADVICE" button gets pushed below the window. This happens because the window has a fixed size, which doesn't account for the text overflow. It should dynamically resize to fit the text.

**Comment by Anish-Mayekar** [comment]
Solved the issue and also add a loading state to know the next advice is loading
